source 'https://rubygems.org'

gem 'middleman'
gem 'middleman-blog'
gem 'middleman-syntax'
gem 'nokogiri'
gem 'susy'
gem 'middleman-favicon-maker'
gem 'middleman-gh-pages'
gem 'builder'
gem 'closure-compiler'